stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'Dinov2withNorm'
    encoder_config_path: 'facebook/dinov2-base'
    encoder_input_size: 224
    encoder_params:
      dinov2_path: 'facebook/dinov2-base'
      normalize: true
    decoder_config_path: 'configs/decoder/ViTXL'
    noise_tau: 0.8
    reshape_to_2d: true

experiment:
  results_dir: '/home/ngothanhnam508/RAE/ckpts/stage1'
  experiment_name: 'celebahq256_dinov2b_decXL'

data:
  source: 'tfds'
  dataset_name: 'celebahq256'
  data_dir: '/home/ngothanhnam508/tensorflow_datasets'
  tfds_builder_dir: '/home/ngothanhnam508/tensorflow_datasets/celebahq256/1.0.0'
  image_size: 256
  num_train_samples: 30000

wandb:
  enabled: false
  entity: ''
  project: 'rae-jax-stage1'
  experiment_name: 'celebahq256_dinov2b_decXL'

training:
  seed: 42
  epochs: 16
  ema_decay: 0.9978
  global_batch_size: 128
  num_workers: 8
  clip_grad: 0.0
  log_interval: 50
  checkpoint_interval: 1
  sample_every: 500
  optimizer:
    lr: 2.0e-4
    betas: [0.9, 0.95]
    weight_decay: 0.0
  scheduler:
    type: cosine
    warmup_epochs: 1
    decay_end_epoch: 16
    base_lr: 2.0e-4
    final_lr: 2.0e-5
    warmup_from_zero: true

gan:
  disc:
    arch:
      dino_ckpt_path: 'models/discs/dino_vit_small_patch8_224.pth'
      ks: 9
      norm_type: 'bn'
      using_spec_norm: true
      recipe: 'S_8'
    optimizer:
      lr: 2.0e-4
      betas: [0.9, 0.95]
      weight_decay: 0.0
    scheduler:
      type: cosine
      warmup_epochs: 1
      decay_end_epoch: 16
      base_lr: 2.0e-4
      final_lr: 2.0e-5
      warmup_from_zero: true
    augment:
      prob: 1.0
      cutout: 0.0
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: 0.75
    perceptual_weight: 1.0
    disc_start: 8
    disc_upd_start: 6
    lpips_start: 0
    max_d_weight: 10000.0
    disc_updates: 1
